### ISSUE TITLE
Installation fail on TS-XL (but should for other) with due to a version too high in kernel revision

### ISSUE THREAD

**Issue by anvgfr** [1000001101000/Debian_on_Buffalo#120]
Trying to deploy current image to a TS-XL R5 with no luck (Buster, or Stretch).

After all setup done, Installer failed with an error "Debootstrap warning" then "Debootstrap Error" during base system installation.

![Capture_install warning](https://user-images.githubusercontent.com/95424421/144436128-a54eed36-8d66-4298-9efe-b3ef08d29bdb.PNG)

Looking at debootstrap log, it complains while installing libc6 with the message attached.

![Capture_debootstrap_log](https://user-images.githubusercontent.com/95424421/144436123-1169c48f-2303-4df9-91cd-7b4317245561.PNG)

The problem seems to be the same as for crouton (https://github.com/dnschneid/crouton/issues/4429)
and link to https://lore.kernel.org/lkml/1612534196241236@kroah.com/

The actual hack is too heavy (depacking the deb on a linux host...)

I don't know what change need to be done for Debian_on_buffalo, but actual uname -a output 4.4.272... so fail with glibc check.

thanks

**Comment by 1000001101000** [comment]
Good to hear from you!

Thanks for digging into the specifics on that! I'll try to find some time to see what we can do about it in the next few days.

**Comment by 1000001101000** [comment]
I was able to recreate the issue on Stretch but not buster. Given the Buster kernels are 4.12.13 and 4.19.208 I wouldn't think they would be affected. 

Either way I'm going to try adjusting the kernel build process to use different naming and generate new kernels/ installer images which should clear things up. I expect I'll do that tomorrow sometime.

**Comment by anvgfr** [comment]
Hello

i wouldn't expected a soo fast reply.. i will try this when new installer
image will be available.

thanks

Le ven. 3 déc. 2021 à 00:14, 1000001101000 ***@***.***> a
écrit :

**Comment by 1000001101000** [comment]
I’ve posted a new stretch installer that works

**Comment by 1000001101000** [comment]
@anvgfr I've posted new installer images for Stretch/Buster/Bullseye which do not have this issue. I've actually resolved the issues preventing this device to work on newer kernels so I highly recommend using the new Bullseye installer if you're still interested.

**Comment by anvgfr** [comment]
Ok, thank you for the job. We have suspended the switch to Linux for the
device, but we perhaps have a try later.

Le lun. 11 avr. 2022 à 23:14, 1000001101000 ***@***.***> a
écrit :
