### ISSUE TITLE
LS-WXL unreachable after reboot

### ISSUE THREAD

**Issue by alphonus** [1000001101000/Debian_on_Buffalo#121]
I used Option 1 to install Debian Buster on my Linkstation. But after the reboot the fans only start spinning up, but it doesnt show up on my local network. Yet the status LED blink. I instructed my router to assign the MAC adress the same ip. Is there a way to debug using a serial connection?

**Comment by 1000001101000** [comment]
Could you describe the partioning/formatting option you chose? This sounds like an incorrectly configured /boot

I’m not aware of anyone connecting a serial console to this model. It was around that era Buffalo started making that difficult.

**Comment by 1000001101000** [comment]
@alphonus Do you still need help with this? I just posted some new installer files which include Bullseye support. As part of the testing I made sure the new installers work on LS-WXL.
