### ISSUE TITLE
LS-X01 Partition Help

### ISSUE THREAD

**Issue by londere** [1000001101000/Debian_on_Buffalo#168]
Hello everyone, recently I get a 'damaged' LS-201 NAS, the issue was the hard drive had die, since when I power on, the device LED's start to blink. So I assume the device works, so the question is: To use Debian distro, which partition table do I need to get the device to work without use the Buffalo tool. 

In advance thanks

**Comment by 1000001101000** [comment]
good to hear from you!

What model is this? LS-XL, LS-210, something else?

**Comment by londere** [comment]
Hello there, it's a ls210d

**Comment by 1000001101000** [comment]
sorry for the delays. 

The only requirements for the partition table/filesystems on that model:

- Must be GPT or MBR. (GPT secondary table needs to either be valid if using GPT and absent if using MBR).
- /boot must be on a separate partition which is relatively small ~1GB
- /boot partition must be partition #1
- /boot must be formatted as ext3
- Drive must be 16TB or less (no usually a problem)

Let me know if you have other questions.

**Comment by londere** [comment]
> sorry for the delays.
> 
> The only requirements for the partition table/filesystems on that model:
> 
> * Must be GPT or MBR. (GPT secondary table needs to either be valid if using GPT and absent if using MBR).
> * /boot must be on a separate partition which is relatively small ~1GB
> * /boot partition must be partition [Network Shut Down #1](https://github.com/1000001101000/Debian_on_Buffalo/issues/1)
> * /boot must be formatted as ext3
> * Drive must be 16TB or less (no usually a problem)
> 
> Let me know if you have other questions.

![image](https://user-images.githubusercontent.com/47585952/215904346-33c065d5-a393-45b4-b9f2-7432a609ebb9.png)
Hi there, I got this over gparted section, as you can see the partition is the first and had 1024 MB named as boot, only I post this if anything is wrong, if not, I only need to put the uImage and initrd corresponding to my device, plug it to Power and Ethernet, wait until I get the IP address and start the ssh installer?

**Comment by 1000001101000** [comment]
That sounds correct.

**Comment by londere** [comment]
> That sounds correct.

OK man I got to boot, but now I had this last problem. Hopefully the last one:

![image](https://user-images.githubusercontent.com/47585952/215918506-07fdf1fa-c78f-4797-b7cb-ca963f64259b.png)

**Comment by 1000001101000** [comment]
When did you download the files? That typically happens when the files are too old. You might just need to download the latest installer files

**Comment by londere** [comment]
It was uploaded in a page in Spanish several months ago, but I had downloaded the last update. Thanks for the support, now I had a new NAS.
