### ISSUE TITLE
button is not useable

### ISSUE THREAD

**Issue by lw65** [1000001101000/Debian_on_Buffalo#19]
After I installed the images step by step, I found that the power button did not respond. I can only shut down through the command line.
In addition, this image has some other problems, such as nodejs can not be used, reported illegal instructions; using aria2 may cause the kernel to crash

so how to enable the button

my device is LS 420d

**Comment by lw65** [comment]
thank you for your response. I will try these

**Comment by 1000001101000** [comment]
any luck?
