### ISSUE TITLE
Failed to create a file system

### ISSUE THREAD

**Issue by TimoEck** [1000001101000/Debian_on_Buffalo#212]
Hey, 

I'm a beginner. It's my first try to change my Linkstation System to Nextcloud. 

The first step is to install ubunto. I followed https://www.youtube.com/watch?v=dfMHlLmsSF8. By Side I checked the wiki (https://github.com/1000001101000/Debian_on_Buffalo/wiki) and followed the way with **Option 1: Load onto Device Running the Stock Firmware**. 

Now I tried to install the ubuntu. Followed the partion advices in the video and set the partions this way:
![1](https://github.com/1000001101000/Debian_on_Buffalo/assets/22869788/eecb71fc-d45a-4732-8e93-677d7f96efb9)
![2](https://github.com/1000001101000/Debian_on_Buffalo/assets/22869788/718c3a69-b640-421c-83a1-6b153edd04be)
![3](https://github.com/1000001101000/Debian_on_Buffalo/assets/22869788/4f160905-aa57-47a8-a5c1-39267a7964a3)

My next Screen and choosed option:
![4](https://github.com/1000001101000/Debian_on_Buffalo/assets/22869788/9af90bc8-6836-4517-88da-17b3a1a502b1)

Next Screen:
![5](https://github.com/1000001101000/Debian_on_Buffalo/assets/22869788/4679d2ad-ee89-4c49-bd1c-6e4f6d93bb18)

And after a while (<1min) Don't be scared my cmd at windows doesn't show right at this install process:
![6](https://github.com/1000001101000/Debian_on_Buffalo/assets/22869788/f68ce015-04ca-4673-aa91-690faa5c259d)

If you need additional information about my system or my installation please let me know. 

additional:
I want to get Raid1. I don't know how to reach this and can I do it now with the partion or later?

**Comment by 1000001101000** [comment]
sda6 and sdb6 are components of RAID#10. if you change those to unused it should be able to move forward.

you can specify a mountpoint for RAID#10 if you wish or you can wait till after you get into debian

**Comment by TimoEck** [comment]
Hello, thank you so much for your fast responde! 

Sorry for my Questions. But I got the RAID#10 "use as: do not use"
![1a](https://github.com/1000001101000/Debian_on_Buffalo/assets/22869788/d728780b-955b-4693-910a-7f3aa03dfded)

If I change RAID#10 to ext4 and the mountpoint to: "/home", will it save all files there 
![2a](https://github.com/1000001101000/Debian_on_Buffalo/assets/22869788/22087aee-d0ba-4cc8-99a1-344dcdd16cb1)

or should I "use as: do not use" for both 2TB Hard Drives?

**Comment by TimoEck** [comment]
I changed RAID#10 to ext4 and tried to set the mountpoint to /mnt/data. 
Changed the filesystem sucessfully, but gave me the same error. "The ext4 file system creation in partition #6 of SCSI1 (0,0,0) (sda) failed.

**Comment by TimoEck** [comment]
Worked. Debian is installed. Thank you very much for your help!
