### ISSUE TITLE
Power Button Detection

### ISSUE THREAD

**Issue by bcoff12** [1000001101000/Debian_on_Buffalo#33]
Thank you for a most excellent project.

I have it up and running on an LS210.  I'd like to sense when the power button is switched to the "off" position.  On the stock firmware the location /proc/buffalo/gpio/switch/power holds the power switch position (on/off).  Is there a way to read that switch in Debian, or has this problem already been solved?

SORRY AFTER POSTING THIS I FOUND THE DOCUMENTATION.

Sorry for the noise.

- Bob Coffman

**Comment by 1000001101000** [comment]
Good to hear from you!

Let me know if you need anything else.
