### ISSUE TITLE
Proposed Wiki updates

### ISSUE THREAD

**Issue by andybjackson** [1000001101000/Debian_on_Buffalo#59]
Afraid Github doesn't seem to allow Wiki edits or pull requests, so I thought I would try to help with some suggested Wiki enhancements and the odd typo.

**On [Preparing Device for Debian Install](https://github.com/1000001101000/Debian_on_Buffalo/wiki/Preparing-Device-for-Debian-Install) there are the following typos**:

- 1st para 3rd bullet "loosing" -> "losing"
- 2nd para "infomration" -> "information"

Consider adding an example configuration to make the choices clear for those who prefer not to leave the installer to do its own thing. Also note that some multi-disk Buffalos require the population of all or at least more than one disk.

First drive
| Order | Path | Purpose | Format | Size | Comment |
| :----: | :--- | :---- | :---: | :---- | :---- |
| 1 | /boot | boot | ext3 | 1GB ||
| 2 | / | root | ext4 | 5GB ||
| 3 | - | swap | - | 1GB | Size of RAM plus a bit? |
| 4 | /[...] | everything else | * | [Rest of drive] | |

Which results in (for a Buffalo with four 500GB drives which can be formatted as desired in Debian when working):
```
SCSI1 (0,0,0) (sda) - 500.1 GB ATA WDC WD5000AAKS-0       ?       ?
>     #1  primary  999.3 MB  B  f  ext3          /boot    ?       ?
>     #2  primary   64.0 GB     f  ext4          /        ?       ?
>     #3  primary    1.0 GB     f  swap          swap     ?       ?
>         pri/log  434.1 GB        FREE SPACE             ?       ?
SCSI2 (0,0,0) (sdb) - 500.1 GB ATA WDC WD5000AAKS-0       ?       ?
>         pri/log  500.1 GB        FREE SPACE             ?       ?
SCSI3 (0,0,0) (sdc) - 500.1 GB ATA WDC WD5000AAKS-0       ?       ?    
>         pri/log  500.1 GB        FREE SPACE             ?       ?
SCSI4 (0,0,0) (sdd) - 500.1 GB ATA WDC WD5000AAKS-0       ?       ?    
>         pri/log  500.1 GB        FREE SPACE             ?       ?
```
And note, as you did for me, that if loading the stock firmware with fewer drives notes about how to do that can be found at:
https://buffalonas.miraheze.org/wiki/Restoring_Stock_Firmware_without_TFTP

specifically, in between booting in EM mode and running the install:
`java -jar acp_commander.jar -t <device ip address> -c "echo MAX_DISK_NUM=2 >> /etc/nas_feature"`

**On [Running the Installer](https://github.com/1000001101000/Debian_on_Buffalo/wiki/Running-the-installer), consider adding the following, which would have assisted me**.

 -  If the installer doesn’t complete, it leaves the ‘installer’ initrd.buffalo & uimage.buffalo. The login is therefore remains user: installer and password: install, rather than the username and password chosen during the install.

I hope this is helpful. Sorry I can't create as a PR for you to consider.

Again many thanks
Andy

**Comment by 1000001101000** [comment]
I've wondered why they have the wiki feature so separate in that regard. Wiki pull requests would be great.

I've been meaning to do a disk layout example for a while. One of these days I need to take a step back and just work on documentation for a while. 

The max disk issue doesn't actually apply to the Debian install process, that's purely an issue with the stock firmware installer. That does remind me that I should do a guide for going from EM mode to the installer.
