### ISSUE TITLE
Uboot Image for Arch Linux on ARM (ALARM)

### ISSUE THREAD

**Issue by sysadminpower2019** [1000001101000/Debian_on_Buffalo#67]
Hello,

thanks for your fantastic job on getting debian to run on buffalo. I got it on my ts-xl and it works great. However the memory and cpu are not really enough to run debian with systemD. 
Is there a way to overclock the cpu a bit?
But most importantly could i ask you to create an image so that we could install Arch or possibly openwrt on the buffalo? That would be a big step plus in getting the most of a really old system.
If you need any support with getting this done please let me know. I'm not much of a dev but im pretty happy to do what i can.

thanks

**Comment by 1000001101000** [comment]
Good to hear from you!

### Overclocking
I only have a vague idea of how this could be accomplished. I would assume it could be done by setting some memory values within the bootloader. Buffalo hasn't published the uboot source for this device which would make it difficult to create a custom version to accomplish this. You might be able to do it from the uboot shell but that would require a full serial console which I haven't done with this device personally.

I have some notes about how a serial console could be set up:
https://buffalonas.miraheze.org/wiki/Terastation_TS-XL#Device_Notes

The datasheet may have clues on how to adjust clock speeds:
https://www.datasheets360.com/pdf/9078526366647279928

### SystemD
I haven't really run into any systemd related issues with devices that have more than 128mb RAM. Although I resisted it at first I've grown to appreciate systemd to a certain degree or at least I don't find it causes as many problems as it is blamed for.

Looking at my TS-XL it currently has 437MB free (512MB total) which seems like a lot to work with for this kind of device. What are you running that you're running out of memory on the device? I'm always curious to hear what people are using the devices for these days, especially if it's something neat I can get them to write a guide for.

In any case it should be possible to switch to an alternative init system under debian, there are guides around for doing that. The main additional thing you'd need to do is recreate the startup and shutdown scripts I have set up as systemd services. 


### Arch/OpenWRT/etc
I actually played around with OpenBSD and Gentoo on some X86 systems earlier this year. I'd like to branch out a little more OS wise but didn't find either of those provided enough advantages to make me want to spend the time getting proficient with them right now. I will probably try arch at some point, but honestly I'm not a big fan of rolling distributions in general. 

I've flashed openwrt on a couple of routers before. It seems like a good fit for that type of device but am unfamiliar with how it handles the types of things I would want from a NAS distro (sata/raid/python/etc).

Technically, you should be able to boot any armv5 distro you want on this device as long as the boot partition is set up properly:

- first partition on MBR or hybrid disk
- <= 1GB
- either standard partition or raid1 member 
- formatted ext3 with inode size=128
- uImage.buffalo containing a kernel (could be mine or based on my config) with support with support for this device in uboot image, with a max size around 4mb I think
- initrd.bufflo containing an initrd (7mb limit) that can support whatever rootfs you use 
 
I'd be willing to help with such an effort but don't know when I could get around to taking it on as a project myself. Right now I've got a pretty long todo list which includes 3 different devices I'm trying to add to the project, adding support for the next Debian version and a handful of issues/improvements for specific devices. 

### notes about this device in particular
There's also issue that currently limits the options for the TS-XL and TS-HTGL(ts2pro) and their rack-mounted variants. for kernel version 4.13 they reworked how a lot of device drivers worked in the linux kernel which broke a bunch of things for these devices. Most have subsequently been fixed but PCI support is still broken for these devices for kernels after 4.12. I hope to someday figure out a fix for the issue but it's beyond my current kernel development skill level.

My understanding is rolling distributions which constantly ship the latest versions of packages which expect the kernel to be updated regularly as well. As such I don't think Arch would be a good fit for this particular device until newer kernels can be made to work with it.
