### ISSUE TITLE
unraid image

### ISSUE THREAD

**Issue by hakimh02** [1000001101000/Debian_on_Buffalo#78]
Hi, this is not really an issue but more of a question. Is it possible to install Unraid instead of Debian? 
Would that need a new boot image? 

Thanks

**Comment by 1000001101000** [comment]
Good to hear from you!

I took a quick look at Unraid's site, it appears to only support X86_64 systems, the devices supported by this project are all ARMv5/ARMv6/ARMv7 (ARMEL and ARMHF).

There are other distros/OS that support these architectures. Off the top of my head Arch,Gentoo,NetBSD and Debian variants like Ubuntu/Raspbian are some of them. Someone could certainly start a project to provide tools to install those OS on these devices. I'd be willing to help with such an effort but would be unlikely to lead it.

Admittedly, If I ever switch my desktops/etc to a different OS I might spin up a project to do the same for Buffalo devices. I did spend some time over the summer trying out Gentoo and FreeBSD both on a Desktop and an X86 Terastation, both were interesting but I didn't find enough advantage to want to move permanently.
