### ISSUE TITLE
How to upgrade LS-WTGL and keep data partitions

### ISSUE THREAD

**Issue by rafalyesware** [1000001101000/Debian_on_Buffalo#95]
I am trying to upgrade a LS-WTGL which doesn't look like it has enough memory to run the installer straight from disk -- it's been sitting around for 18 hours and still hasn't gotten an IP.  But what I'd like to do is upgrade the `/` and `/boot` partitions but leave the data on the "data" partition alone, much the way I did with the online installer on my LS-WVL.  But, it looks like the `debootstrap` builds an image that's expected to be written to the base disk and thus overwrites existing partition layout etc.

Caveats:
  * The NAS box has 2 drives, and I don't have enough SATA adapters to connect both of them to the laptop.  I assume this is surmountable by converting one disk, rebooting and marking the missing halves of the root / boot partitions as failed and then re-syncing once the non-converted disk is re-inserted.

My plan for recovering is the following -- I'd just like to get confirmation that this sounds sane and/or a redirect if there's an easier way to do it:

1. Run `debootstrap` to generate the image for the LS-WTGL.
2. Mount the image as a loopdev, the disk from the NAS box
3. Create new ext3 filesystems on the root / boot MD partitions on the NAS disk.
3. `dump` from the root partition of the image, restoring to the root MD partition on the NAS disk.
4. Re-insert the newly updated disk in the NAS, let it boot, mark the missing halves of the MD partitions as failed.
5. Insert the non-updated disk and re-sync the MD sets to the second disk.
6. Proceed with post-install steps as usual after `debootstrap` install.

Does that sounds reasonable?  I thought about hardcoding the partition sizes to the exact sizes that match the on-disk layout, building the image and dd'ing it to the raw disk and then manually re-adding the "data" partition after, but am a little worried that some math in the script would create partitions that are just a little larger and thus trash my data.  Other thoughts welcome, too!

I guess the other question is whether I should consider using Stretch vs. Buster on the LS-WTGL, or once things are set up does it not matter as much?  Again, thinking about memory usage on this piddly device.

**Comment by 1000001101000** [comment]
Good to hear from you!

The approach you describe could work though I've never actually used dump so I'm not certain. If you end up with different UUIDs for the filesystems you'd need to update the fstab and generate a new initrd.

I suppose rather than dump you could set up the script to create slightly smaller partitions, then dd the resulting filesystems to the existing MD devices and expand them later. You'd want to adjust mdadm.conf later but I think you should be able to boot successfully without doing so.

Also, how are your data partitions set up. Is this RAID0, RAID1 or separate partitions? If this model creates partitions that are too small for Debian you may need to adjust your approach further. 

Which version you use depends on your use case, each newer version comes with OS-level improvements but also needs more memory to run. Stretch will likely still get security updates for a few more years, so if you run into problems with Buster it's still a viable fallback option.

If you have any spare disks I'd recommend doing some experiments before moving forward.

**Comment by rafalyesware** [comment]
Thanks for being super-responsive here!  Appreciate these boxes getting a new life... both of the NAS boxes were packed up when we did some house construction but there's a lot of data on them I didn't have except on a backup drive that wasn't so easy to access it from... and seeing how easy it is to run all sorts of network services on my Raspberry Pis, I was starting to hate having to work around Buffalo's firmware to make these useful again 😬 

Thanks for the point re: updating `initrd` for new UUIDs, that was vaguely in the back of my head, but I'll add it as an explicit step to check / update `/etc/fstab` if needed.

The partition setup on the box right now should be perfect, it's the same as on my LS-WVL -- RAID 1 with ~ 1G `/boot` and swap and ~ 5G `/`, with the rest of the disk a RAID1 data partition.  

I did actually specify slightly smaller partitions in the script than what's on the disk (because the sizes on disk aren't even MB's), so I like the idea of just `dd`ing each filesystem to the appropriate device and cleaning up the slop later via resize... that is probably much easier than `dump`/`restore` and hopefully *also* preserves UUIDs, so should cut a few steps out of the process.

Since I've got 2 disks, I can experiment on one and keep the other "clean" or even restore it to factory if need be (🤞 that this isn't necessary!)

Cheers, thanks!

**Comment by 1000001101000** [comment]
Nice!

It might just be the old Terastation II with the tiny root partition, it seems every time I forget to mention it I happen to be talking to someone with an affected model.

RaspberryPi alternatives is part of what got me interested in these devices (that and I owned one at the time). For most of the project's I was interested in at the time having a hard rather than an unreliable SD card made them way more useful than a RaspberryPi for most applications. Most anything requiring exposed GPIO pins was better off using an Arduino anyway.

**Comment by rafalyesware** [comment]
The thing I love about the RPis is that it's not much more $$$ to power them via POE, so I now have a 3B and a 4B powered via the switch, which makes it super-nice to both monitor power draw and run a flock of them without a mess of cabling.  And with the right USB-to-SATA adapter the 4 can boot directly off USB (I suspect I could make the 3 do so as well, but the disk it's currently attached to is a Mac backup drive, so formatted as HFS and I don't want to have to re-do that).


But it

**Comment by 1000001101000** [comment]
Yeah, RaspberryPi's have gotten more and more useful while the "hackible" Linkstations have continued to age. Back then you would also see a lot of used Linkstations for sale on ebay for <$10 since people couldn't figure out how to re-load the firmware when the drives died (at least I've always assumed that's why). If I was working on the same projects today I would probably have taken a different path.

**Comment by rafalyesware** [comment]
For the record, here's my recipe so far.  I used an Ubuntu 18 VM I used for other embedded dev to do this.

1. Build appropriate image using ./generate_disk_image.sh
2. Save the metadata and then re-create RAID metadata for /boot, / (and SWAP?) partitions

Boot:
`# mdadm --examine /dev/sdb1 > boot.raid.metadata`
`# mdadm -C /dev/md0 --metadata=0.90 -l 1 -n 1 /dev/sdb1 --force`

Root:
`# mdadm --examine /dev/sdb2 > root.raid.metadata`
`# mdadm -C /dev/md1 --metadata=0.90 -l 1 -n 1 /dev/sdb2 --force`

I did SWAP too, but that probably could have been left alone:
`# mdadm --examine /dev/sdb5 >swap.raid.metadata`
`# mdadm -C /dev/md10 --metadata=0.90 -l 1 -n 1 /dev/sdb5 --force`

Data partition RAID config is left since we’re not touching that; this way it should be ready to simply re-add when the system is re-assembled after the disk re-install and not require any re-sync.

Mount the generated image as a loopback device:
`# losetup -f -P debian_buster_armel.img`

Clone boot partition from md90 to md0:
`# dd if=/dev/md90 of=/dev/md0 bs=4k`

Clone root partition from md92 to md1:
`# dd if=/dev/md92 of=/dev/md1 bs=4k`

Format swap partition so it’s clean:
`# mkswap /dev/md10`

Check things look OK:
`# mkdir -p /mnt/md90 /mnt/md92 /mnt/md0 /mnt/md1`
`# mount /dev/md90 /mnt/md90`
`# mount /dev/md92 /mnt/md92`
`# mount /dev/md0 /mnt/md0`
`# mount /dev/md1 /mnt/md1`

(Look around, compare filesystems, etc.)

Now clean up the mounts:
`# umount /mnt/md90`
`# umount /mnt/md92`
`# umount /mnt/md0`
`# umount /mnt/md1`

…and the md devices:
`# mdadm —stop /dev/md90`
`# mdadm —stop /dev/md92`
`# mdadm —stop /dev/md0`
`# mdadm —stop /dev/md1`
`# mdadm —stop /dev/md10`

Check /proc/mdstat and stop whatever device the data partition got assigned too.
`# mdadm —stop /dev/md127`

Tear down the loopback mount of the image file
`# losetup -D`

Reboot, disconnect disk, insert back into LinkStation

So far so good, as long as I'm booting just off one disk.  If I attach both disks, I end up in the same state I was in with the initial installer -- LinkStation is chugging along and touching the disk but no IP is ever requested... maybe it's running disk checks, or re-syncing the (large-ish) data array?  I disconnected the second disk, reconnected it to my laptop and zeroed out the MD superblocks on the `/boot` and root partitions via:

`# mdadm --zero-superblock /dev/sdb1`
`# mdadm --zero-superblock /dev/sdb2`
`# mdadm --zero-superblock /dev/sdb5`

which left just the data partition and it's raid slice.  Re-inserted disk into the NAS and am in the same state again.  Each time I've removed /disconnected the second disk, the NAS boots up to network connectivity fine, so it's not like I screwed something up in the install.  🤔

**Comment by 1000001101000** [comment]
Sounds like progress.

Did you say that you've got the Debian install working from a single disk? 

The bootloader on these devices has some quirks with how it scans for boot partitions and decides where to boot from. There are several scenario where having a disk with a partition 1 which is unsuitable to boot from can cause the boot process to fail even if the other disk is valid. 

If you don't need anything from your second disk the easiest way forward is probably:
- completely remove the partition table from disk two
- it should boot from disk one if there is no partition 1 (or just no partition table) on disk 2 
- once in Debian copy the partition table from disk1 to disk2 
- add each partition to the appropriate raid array and wait for resync to complete.

**Comment by rafalyesware** [comment]
Also worth noting that when I created the `debootstrap` image, I had entries in the `mdadm.conf` for both the `md9*` RAID devices it creates and the `md0`, `md1`, `md2`, `md10` devices on the attached disk, so I had to clean that up and then re-ran `/usr/sbin/update-initramfs -u`.  I guess that means the order of steps required the NAS disk to be connected before I built the image.

**Comment by rafalyesware** [comment]
> Sounds like progress.

Definitely!

> Did you say that you've got the Debian install working from a single disk?

Yep, works perfectly!

> The bootloader on these devices has some quirks with how it scans for boot partitions and decides where to boot from. There are several scenario where having a disk with a partition 1 which is unsuitable to boot from can cause the boot process to fail even if the other disk is valid.
> 
> If you don't need anything from your second disk the easiest way forward is probably:
> 
> * completely remove the partition table from disk two
> * it should boot from disk one if there is no partition 1 (or just no partition table) on disk 2
> * once in Debian copy the partition table from disk1 to disk2
> * add each partition to the appropriate raid array and wait for resync to complete.

Ooh this would have been much better than zeroing out the superblocks of the RAID partitions separately, since then I can do all the repairs on the LS with both disks connected.  Will give that a go this evening, thanks!

**Comment by rafalyesware** [comment]
FWIW, I seem to remember having similar issues when I upgraded the disks in the NAS a long time ago when one failed -- also had to zero out everything on the second disk or I couldn't rebuild either... so 🤞 that this will make it go!

**Comment by rafalyesware** [comment]
OK, I was impatient so had to give it a whirl when I had a break from work.  TL;DR - removing the second disk's partition table and re-inserting the disk in the NAS let it boot happily.  Since I had to yank the disk to zero the partition table I just `dd`ed off the first two 512 blocks before zeroing them, and then restored them via `dd` again once the LS booted.

Notes: I had to `apt-get install parted` to get the `partprobe` tool so I could force the kernel to re-read the partition table after the `dd`, since I didn't want to get stuck in the infinite-reboot again just to see the updates.  My data RAID is now happy, and I'm about to `--grow` the boot/root/swap partitions into rull RAID1-ness.

Thanks for all the tips!

**Comment by rafalyesware** [comment]
> Notes: I had to `apt-get install parted` to get the `partprobe` tool so I could force the kernel to re-read the partition table after the `dd`, since I didn't want to get stuck in the infinite-reboot again just to see the updates.

If I'd followed the post-install instructions in https://github.com/1000001101000/Debian_on_Buffalo/wiki/Alternate-install-method-via-debootstrap-script#copy-partitions-to-additional-disks I probably wouldn't hav needed that.  Didn't realize that `gdisk` had all those fancy expert options!  TIL!

**Comment by rafalyesware** [comment]
Also, now that the system is up and running I realized that the LS-WTGL actually has 128MB memory, I am wondering if the initial non-responsiveness to `initrd` based installer was the same issue that kept the NAS from booting with the second disk in after I flashed the upgraded images to `/` and `/boot`.  I would think it would have been fine since the `initrd` and `uImage` files were loaded via SCP using Buffalo's stock kernels and no RAID-muckery was done, but who knows.  I'll need to do some more testing with reboots / powerdowns to make sure it comes up fine now that all RAID arrays are fully operational.

**Comment by 1000001101000** [comment]
gdisk is one of my favorite tools, it seems to have a feature for everything you'd ever want to do to a partition table.

That model is one of the few I've never tested with, I'm not sure I've even heard from someone using that model before.  Since the process for booting the installer is the same as booting Debian I would assume the installer image would be fine for that model if Debian is working but I'm not 100% certain.

The most common failure at that point is folks downloading the page HTML from github rather than the installer images themselves.

**Comment by rafalyesware** [comment]
> gdisk is one of my favorite tools, it seems to have a feature for everything you'd ever want to do to a partition table.

Fom the help in `expert` mode, definitely!

> That model is one of the few I've never tested with, I'm not sure I've even heard from someone using that model before. Since the process for booting the installer is the same as booting Debian I would assume the installer image would be fine for that model if Debian is working but I'm not 100% certain.

The good news is that once booted everything seems to Just Work!  And like you I would have assumed that just replacing the `uImage` and `initrd` on the `/boot` partition would have been as safe a process as there is.

> The most common failure at that point is folks downloading the page HTML from github rather than the installer images themselves.

Definitely not guilty on that count 😆 -- downloaded them on my Mac and scp'd them to the NAS box:

```
(base) rafal@RBONI-MBP Downloads % file initrd.buffalo uImage.buffalo
initrd.buffalo: u-boot legacy uImage, debian-installer ramdisk, Linux/ARM, RAMDisk Image (gzip), 6762904 bytes, Mon Mar 22 07:28:38 2021, Load Address: 0x00000000, Entry Point: 0x00000000, Header CRC: 0xE904415E, Data CRC: 0x1596C639
uImage.buffalo: u-boot legacy uImage, Debian kernel, Linux/ARM, OS Kernel Image (Not compressed), 2062730 bytes, Mon Mar 22 07:28:38 2021, Load Address: 0x01A00000, Entry Point: 0x01A00000, Header CRC: 0xA10E24B3, Data CRC: 0xD5A472BF
```

**Comment by rafalyesware** [comment]
I'll play around with rebooting / powering down to make sure things are fine and if I find anything useful will report back here.  I noticed that the installer `initrd` is only ~ 250k bigger than the current `initrd` image it booted fine with (6762904 bytes vs. 6513917 bytes), but who knows what the `uBoot` limitations on that box are... 

Also realized as I was thinking this through that  if the installer image *was* the problem that inserting the second disk (before I wiped the partition table) might have booted that somehow since that `/boot` partition still had the installer image on it.. but that's just more theorizing.

**Comment by 1000001101000** [comment]
I don't know if I had it in the instructions or not, but generate a new initrd once you're up and running. It will likely be smaller and the device will boot faster as a result.

**Comment by rafalyesware** [comment]
Thanks for the hint re: the initrd.  I did regenerate it, but it's still just about as chunky as before.  Still other than the longish boot time making me occasionally freak out that the box is stuck in "perma-boot" again, it's been fine.  Installed `minidlna` and have all my taped shows back online, monitoring it via `prometheus-node-exporter` so I have more stats than I can shake a stick at (except no CPU/chasis temp stats), I'm pretty happy.  Next step is to get Samba set up with a centralized auth server so I can keep user accounts in a single place.

**Comment by 1000001101000** [comment]
That device's boot loader may have a ~7MB initrd limit. It seems like something is making yours larger than I would expect, it's only a problem if a future change makes it even bigger but having the boot loader crash is a pain to recover from.

The first thing I'd check is that you are using MODULES=dep rather than MODULES=most in the initramfs-tools config.

You can also  switch to xz compression to make it smaller (though they take a while to generate). I've got notes on how to do that here:
https://github.com/1000001101000/Debian_on_Buffalo/issues/62#issuecomment-713225833

**Comment by rafalyesware** [comment]
Oh, yeah, the default appears to be `MODULES=most` and I hadn't updated it.  Looks like the update was unhappy, though:

```
root@ark:/home/rafal# dpkg-reconfigure  linux-image-4.19.0-16-marvell
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-4.19.0-16-marvell
I: The initramfs will attempt to resume from /dev/md10
I: (UUID=85c5fd40-928d-48c5-be2e-339e4fb14514)
I: Set the RESUME variable to override this.
Using DTB: orion5x-linkstation-lswtgl.dtb
Installing /etc/flash-kernel/dtbs/orion5x-linkstation-lswtgl.dtb into /boot/dtbs/4.19.0-16-marvell/./orion5x-linkstation-lswtgl.dtb
Taking backup of orion5x-linkstation-lswtgl.dtb.
Installing new orion5x-linkstation-lswtgl.dtb.
Installing /etc/flash-kernel/dtbs/orion5x-linkstation-lswtgl.dtb into /boot/dtbs/4.19.0-16-marvell/./orion5x-linkstation-lswtgl.dtb
Taking backup of orion5x-linkstation-lswtgl.dtb.
Installing new orion5x-linkstation-lswtgl.dtb.
flash-kernel: deferring update (trigger activated)
/etc/kernel/postinst.d/zz-flash-kernel:
Using DTB: orion5x-linkstation-lswtgl.dtb
Installing /etc/flash-kernel/dtbs/orion5x-linkstation-lswtgl.dtb into /boot/dtbs/4.19.0-16-marvell/./orion5x-linkstation-lswtgl.dtb
Taking backup of orion5x-linkstation-lswtgl.dtb.
Installing new orion5x-linkstation-lswtgl.dtb.
Installing /etc/flash-kernel/dtbs/orion5x-linkstation-lswtgl.dtb into /boot/dtbs/4.19.0-16-marvell/./orion5x-linkstation-lswtgl.dtb
Taking backup of orion5x-linkstation-lswtgl.dtb.
Installing new orion5x-linkstation-lswtgl.dtb.
flash-kernel: deferring update (trigger activated)
Segmentation fault
```

I'll have to load `gdb` and see what that's about.

**Comment by 1000001101000** [comment]
weird, might be worth uninstalling/reinstalling flash-kernel. I'd assume the cause is some package wasn't updated and is incompatible with libc.... or something like that.

I ran into some things vaguely like that with my PC, so far just uninstalling the broken package and re-installing has always worked.

**Comment by rafalyesware** [comment]
Ha, while installing `gdb`, `dpkg` also did a reconfigure and that time things worked.  It looks like if I removed `raid456` and `raid10` I could lose lots of dependencies (and those modules aren't that small themselves).  The biggest hog of module space is XFS, but the data drive is XFS'ed, so 🤷 .  The crypto modules aren't so big, but there are a bunch of them.

Here's the list sorted by size:

```
Module                  Size  Used by
xfs                   917504  1
ext4                  532480  2
ipv6                  409600  32
scsi_mod              180224  3 sd_mod,libata,sg
libata                180224  3 ahci,libahci,sata_mv
usbcore               172032  2 ehci_orion,ehci_hcd
raid456               147456  0
md_mod                126976  10 raid1,raid10,multipath,linear,raid0,raid456
dm_mod                106496  0
raid6_pq               98304  3 async_pq,raid456,async_raid6_recov
jbd2                   90112  1 ext4
thermal_sys            65536  1 gpio_fan
ehci_hcd               61440  1 ehci_orion
raid10                 53248  0
mtd                    49152  10 m25p80,ofpart,cmdlinepart,mtdblock,physmap_of,mtd_blkdevs
sd_mod                 45056  10
raid1                  40960  4
cfi_cmdset_0002        40960  1
af_packet              40960  2
mv643xx_eth            36864  0
marvell_cesa           36864  0
autofs4                36864  2
spi_nor                32768  1 m25p80
sg                     32768  0
sata_mv                32768  8
libahci                28672  1 ahci
x_tables               24576  1 ip_tables
fscrypto               24576  1 ext4
evdev                  24576  1
des_generic            24576  1 marvell_cesa
ahci                   24576  0
sha256_generic         20480  1
raid0                  20480  0
mtd_blkdevs            20480  1 mtdblock
marvell                20480  1
jedec_probe            20480  0
ip_tables              20480  0
gpio_keys              20480  0
xor                    16384  1 async_xor
usb_common             16384  1 usbcore
rtc_rs5c372            16384  0
physmap_of             16384  0
ofpart                 16384  0
nls_base               16384  1 usbcore
mvmdio                 16384  0
multipath              16384  0
mtdblock               16384  0
mbcache                16384  1 ext4
m25p80                 16384  0
linear                 16384  0
libcrc32c              16384  2 xfs,raid456
leds_gpio              16384  0
hwmon                  16384  2 thermal_sys,gpio_fan
hmac                   16384  2
gpio_fan               16384  0
gen_probe              16384  1 jedec_probe
ehci_orion             16384  0
ecb                    16384  0
crc32c_generic         16384  4
crc16                  16384  1 ext4
cmdlinepart            16384  0
chipreg                16384  2 jedec_probe,physmap_of
cfi_util               16384  2 cfi_cmdset_0002,jedec_probe
async_xor              16384  3 async_pq,raid456,async_raid6_recov
async_tx               16384  5 async_xor,async_pq,raid456,async_memcpy,async_raid6_recov
async_raid6_recov      16384  1 raid456
async_pq               16384  2 raid456,async_raid6_recov
async_memcpy           16384  2 raid456,async_raid6_recov
```

**Comment by rafalyesware** [comment]
Anyway, for now I'm going to just `xz` it and play with module selection as a second step.

**Comment by 1000001101000** [comment]
module selection gives you pretty big advantages basically for free, though as you've noticed it'll still keep a bunch of the modules but does a pretty good job of restricting to just what is needed to get the rootfs online and can then load the stuff needed for network/data drive etc later.

I use XZ for most of my devices since you don't generate new initramfs very often, but it does slow down the process by as much as a few minutes on some devices.

**Comment by 1000001101000** [comment]
....that reminds me.... my laptop spends most of its boot time at "loading initramfs" at the end of grub. It only lasts like 15 seconds but it bothers me every time for some reason. One of these days I need to figure out why that is, I tried these same steps which made it much smaller but that didn't make a difference. I'm guessing loading an inird from an ssd to ddr4 ram isn't nearly the bottleneck as on these embedded devices.

**Comment by rafalyesware** [comment]
> Oh, yeah, the default appears to be `MODULES=most` and I hadn't updated it.

Oops, I was wrong.  It's `most` in the `initramfs.conf` but was being overridden by `/etc/initramfs-tools/conf.d/modules` anyway... so it now makes sense why nothing was shrinking.  You have a good point re: module selection being free, and it should actually speed up the build as well as load, so I guess I'll have a whack at `MODULES=list`.

**Comment by 1000001101000** [comment]
I mostly only use list in the debootstrap since the PC running it typically doesn't have marvell sata adapters. On devices I've alway used and been happy with "dep" but list might be even better if you want to go that route (you just might have a failed boot if you overlook something). 

Another thing to consider (though somewhat unlikely).... occasionally module names change between kernel versions. I beleive if you had used list with a 3.xx kernel is would fail now because some of the marvell modules were renamed. That could happen again someday .... something to think about if you move to 5.xx 6.xx etc someday.

**Comment by rafalyesware** [comment]
Oh, yeah, name changes in modules and having to deal with them would suck, esp. without console.  OK, I'm happy to keep it with `MODULES=dep` and just up the compression.  Thanks for all the extra hints!

**Comment by rafalyesware** [comment]
Also, worth pointing out that in https://github.com/1000001101000/Debian_on_Buffalo/issues/62#issuecomment-713225833 the quotes around the contents of the lines in `/etc/initramfs-tools/conf.d/compress` cause it to fail.  It needs to just be the raw settings.

**Comment by 1000001101000** [comment]
I must have pulled that out of the script I was using to generate the file or something. I went ahead and updated that comment since I keep linking to it.

**Comment by 1000001101000** [comment]
I was originally planning to set this up by default as part of my installer, I probably will when I get around to working on Bullseye. I suspect it may become mandatory for some devices/configs to work.
